ModelName: qwen2.5:3b
SystemPath: 
  Programs: 
   Paths:
    - C:\Users\Administrator\AppData\Roaming\Microsoft\Windows\Start Menu
    - C:\ProgramData\Microsoft\Windows\Start Menu\Programs
   Exclude:
    Name: 卸载,Installer, Help,配置工具,Uninstall,Release Notes,FAQ,ReadMe,User’s Guide
    Path: Windows Kits,Git,MySQL Server 8.0,Stardock,Tesseract-OCR,Visual Studio 2022